default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogkadai_development

test:
  <<: *default
  database: blogkadai_test


production:
  <<: *default
  database: blogkadai_production
  username: blogkadai
  password: <%= ENV['BLOGKADAI_DATABASE_PASSWORD'] %>
